# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180702_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='Getvero_key',
            new_name='getvero_key',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='getvero_username',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
